### ISSUE TITLE
Your device isn't compatible with this version

### ISSUE THREAD

**Issue by marcpinet** [UniceApps/UniceNotes#14]
**Describe the bug**
As an old student from IUT Nice Côte d'Azur, I couldn't resist checking out the new students' projects.

Anyway, it seems your app isn't available for download on the Play Store.
I tried many Android APIs such as 25 (Android 7 Nougat), 29 (Android 10 Pie) and 33 (Android 13 Tiramisu).
The phone used were Pixel 2 (emulated) for both API 25 and 29 and a real Pixel 7 for API 33.

**To Reproduce**
Just go to the Play Store.

**Expected behavior**
The app should be available for download on every devices (or at least for Android 10+)

**Screenshots**
![image](https://github.com/UniceApps/UniceNotes/assets/52708150/4aa9df34-18cf-4919-83ec-06424c9b12c2)

**Smartphone**
 - Device: Emulated Pixel 2 and a real Pixel 7
 - iOS / Android version: Android 7, 10 and 13

**Comment by hugofnm** [comment]
Hi @marcpinet, 
Thanks for (trying) reviewing my first app !

The UniceNotes application aims to be universal, hence the use of the React Native Framework. As a (novice) developer, I try to make the application as open and easy to access as possible. But sometimes my application may encounter technical or software limitations.

**About the emulated phone :**
In fact, as the app handle very sensitive data stored in-device (such as usernames and passwords), I cannot let unverified devices download the app through the Play Store (emulated devices, rooted devices or devices without a valid installation of the Google Play Services).

> Réduisez les risques pour votre appli en arrêtant la distribution Play sur les appareils et les environnements virtuels qui échouent aux contrôles d'intégrité du système, qui ne répondent pas aux exigences de compatibilité Android et qui ne disposent peut-être pas de la licence nécessaire pour exécuter les services Google Play. 
> Google Play vérifiera que l'appareil respecte l'intégrité de l'appareil avant de rendre votre appli visible par les utilisateurs
[From the API Play Integrity](https://support.google.com/googleplay/android-developer/answer/11395166#set_up_device_exclusion)

**About the real phone :**
After looking through the Google Play Console, it is kinda strange to see the app being blocked for such a popular phone. I test all the releases with a Samsung Galaxy S10 and I know quite a few people using the app with different brands (even a Pixel 6 was able to download the app). 

The app is configured to work with the followings :
```
Plates-formes natives
arm64-v8a, armeabi-v7a, x86, x86_64
Niveaux d'API
21+
SDK cible
33
```

So, I can't really tell you why it isn't working for you.

Thanks anyway for the feedback :). I will see what I can do on my side. 
I will leave this issue opened until I find a fix.

PS: If you really want to try my app I'll try to put an APK here for version 1.4.0.

**Comment by marcpinet** [comment]
Maybe I should have mentionned that my phone is rooted

**Comment by hugofnm** [comment]
Yeah, I think the fact that you use a rooted version of Android maybe is the reason of why Play Store doesn't let you install the app. 

I don't think that the YASNAC test made by an third party app is reliable : see https://github.com/RikkaW/YASNAC/issues/33 

This app seems to test SafetyNet API which is deprecated : https://developer.android.com/training/safetynet/deprecation-timeline
and the UniceNotes app works with the Play Integrity API (not tested with YASNAC)

Here is a preview of the 1.4.0 as an apk file : (availability 24h)
https://expo.dev/accounts/hugofnm/projects/unicenotes/builds/62dd1f68-14af-411b-8a3c-4d889e93bf42
